services:
  xray:
    image: ghcr.io/xtls/xray-core:26.2.6
    container_name: xray-test
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./docker/xray/config:/usr/local/etc/xray/config:ro
    command: run -confdir /usr/local/etc/xray/config
  
  scd:
    build:
      context: ./scd
    container_name: scd
    depends_on:
      - xray
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:8080"
    volumes:
      - ./docker/scd/config.yml:/app/config/config.yml:ro
  sfc:
    build:
      context: ./sfc
    container_name: sfc
    restart: unless-stopped
    ports:
      - "127.0.0.1:9091:8080"
    volumes:
      - ./docker/sfc/config.yml:/app/config/config.yml:ro
