subscriptions:
  - id: local-vpn
    input: /app/data/vpn
    enabled: true
    format: auto
    fetchTimeoutMs: 5000
    # filters:
    #   countryAllowlist:
    #     - DE
    #     - NL
    #   labelIncludeRegex: '/,\\s*Extra(?!\\s*Whitelist)\\s*$/i'
    targets:
      - address: xray:8080
        timeoutMs: 5000
        fixedOutbounds:
          - direct
          - blocked
        observatorySubjectSelectorPrefix: x-observe-

runtime:
  mode: daemon
  schedule: "*/5 * * * *"

logging:
  level: info
  format: json

resources:
  outbounds:
    enabled: true
